# Credit Card Fraud Detection System

## Task 1: Data Import and Merging

The first step of this analysis is to import the provided datasets and combine them into a single dataset for further processing. Two datasets were provided, each containing related information about customers and their financial attributes.

Both datasets were loaded into the Python environment using the pandas library. Since the datasets share a common identifier, they were merged using the "ID" column as the primary key.

Merging the datasets ensures that all relevant information is available in one place, which is essential for accurate analysis and model building. After merging, the dataset was checked to confirm that the operation was successful and that no duplicate records were introduced.

In [1]:
#Load Data
import pandas as pd
df1 = pd.read_csv("Credit_Card_Dataset_2025_Sept_1.csv")
df2 = pd.read_csv("Credit_Card_Dataset_2025_Sept_2.csv")

print("Dataset 1 shape:", df1.shape)
print("Dataset 2 shape:", df2.shape)

Dataset 1 shape: (25134, 17)
Dataset 2 shape: (25134, 4)

In [2]:
df1.head()

,Unnamed: 0,ID,GENDER,CAR,REALITY,NO_OF_CHILD,FAMILY_TYPE,HOUSE_TYPE,FLAG_MOBIL,WORK_PHONE,PHONE,E_MAIL,FAMILY SIZE,BEGIN_MONTH,AGE,YEARS_EMPLOYED,TARGET
0,0,5008806,M,Y,Y,0,Married,House / apartment,1,0,0,0,2.0,29,59,3.0,0
1,1,5008808,F,N,Y,0,Single / not married,House / apartment,1,0,1,1,1.0,4,52,8.0,0
2,2,5008809,F,N,Y,0,Single / not married,House / apartment,1,0,1,1,1.0,26,52,8.0,0
3,3,5008810,F,N,Y,0,Single / not married,House / apartment,1,0,1,1,1.0,26,52,8.0,0
4,4,5008811,F,N,Y,0,Single / not married,House / apartment,1,0,1,1,1.0,38,52,8.0,0

In [3]:
df2.head()

     INCOME INCOME_TYPE     User                 EDUCATION_TYPE
0  202500.0     Working  5150487  Secondary / secondary special
1  157500.0     Working  5150485  Secondary / secondary special
2  157500.0     Working  5150484  Secondary / secondary special
3  157500.0     Working  5150483  Secondary / secondary special
4  157500.0     Working  5150482  Secondary / secondary special

In [4]:

print(df1.columns)
print(df2.columns)

Index(['Unnamed: 0', 'ID', 'GENDER', 'CAR', 'REALITY', 'NO_OF_CHILD',
       'FAMILY_TYPE', 'HOUSE_TYPE', 'FLAG_MOBIL', 'WORK_PHONE', 'PHONE',
       'E_MAIL', 'FAMILY SIZE', 'BEGIN_MONTH', 'AGE', 'YEARS_EMPLOYED',
       'TARGET'],
      dtype='str')
Index(['INCOME', 'INCOME_TYPE', 'User', 'EDUCATION_TYPE'], dtype='str')

In [5]:
df1 = df1.drop(columns=['Unnamed: 0'])

An unnecessary column named "Unnamed: 0" was identified in the dataset. This column was likely created during the data export process and does not provide any meaningful information for analysis.

Therefore, it was removed to improve data quality and ensure that only relevant features are used in further analysis and model building.

In [6]:
len(set(df1['ID']).intersection(set(df2['User'])))

25134

To ensure that the datasets can be merged correctly, the common values between the key columns were examined. The intersection between the ID column in the first dataset and the User column in the second dataset was calculated.

This step helps to confirm whether both datasets share matching records and ensures that the merge operation will be meaningful.

In [7]:
#merge Data
merged_df = pd.merge(df1, df2, left_on='ID', right_on='User', how='inner')

The datasets were merged using the "ID" column from the first dataset and the "User" column from the second dataset. Since the column names differ, the merge was performed using the left_on and right_on parameters.

An inner join was used to ensure that only matching records from both datasets are included in the final dataset. This helps to maintain data consistency and avoids introducing missing values from unmatched records.

In [8]:
print("Merged dataset shape:", merged_df.shape)

Merged dataset shape: (25134, 20)

In [9]:
print("Duplicate IDs:", merged_df['ID'].duplicated().sum())

Duplicate IDs: 0

In [10]:
merged_df = merged_df.drop(columns=['User'])

In [11]:
#Save merged data set
merged_df.to_csv("merged_dataset.csv", index=False)

In [12]:
print(merged_df.shape)
print(merged_df.columns)
print(merged_df.dtypes)

(25134, 19)
Index(['ID', 'GENDER', 'CAR', 'REALITY', 'NO_OF_CHILD', 'FAMILY_TYPE',
       'HOUSE_TYPE', 'FLAG_MOBIL', 'WORK_PHONE', 'PHONE', 'E_MAIL',
       'FAMILY SIZE', 'BEGIN_MONTH', 'AGE', 'YEARS_EMPLOYED', 'TARGET',
       'INCOME', 'INCOME_TYPE', 'EDUCATION_TYPE'],
      dtype='str')
ID                  int64
GENDER                str
CAR                   str
REALITY               str
NO_OF_CHILD         int64
FAMILY_TYPE           str
HOUSE_TYPE            str
FLAG_MOBIL          int64
WORK_PHONE          int64
PHONE               int64
E_MAIL              int64
FAMILY SIZE       float64
BEGIN_MONTH         int64
AGE                 int64
YEARS_EMPLOYED    float64
TARGET              int64
INCOME            float64
INCOME_TYPE           str
EDUCATION_TYPE        str
dtype: object